<a href="https://colab.research.google.com/github/cecordobat/MSc_Computer_Enginnering_DS/blob/main/S1_M1/NBK_Tarea_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = "https://drive.google.com/uc?export=view&id=13qgLt1GChCQgM3eb5SU5PoZjR7NYmSil" alt = "Encabezado MLDS" width = "100%">  </img>

# **Tarea 1 - Introducción al análisis de datos: *Python* y *NumPy***
---
Esta tarea le permitirá practicar y aplicar las habilidades adquiridas para la escritura de código en el lenguaje de programación *Python* y su librería de numérica *NumPy*.

> **Nota:** Esta tarea va a ser calificada estableciendo una conexión con **[UNCode](https://juezun.github.io/)**. La conexión se realizará al ejecutar la celda indicada e ingresando los datos de usuariio.En cada ejercicio se indicará si es calificable o no, también los lugares donde debe escribir su código sin modificar lo demás con un aproximado de cantidad de líneas a escribir. No se preocupe si su código toma más líneas, esto es simplemente un aproximado destinado a que pueda replantear su estrategia si el código está tomando más de las esperadas. No es un requisito estricto y soluciones más largas también son válidas.

> **La tarea es incremental, es recomendable resolver los puntos en orden.**

> En caso de tener dudas de cómo solucionar este tipo de ejercicios, por favor consultar el demo en la unidad 0

Ejecute las siguientes celdas para importar las librerías y conocer sus respectivas versiones.

In [6]:
import numpy as np

In [7]:
!python --version
print('NumPy', np.__version__)

Python 3.10.12
NumPy 1.26.4


Este material fue realizado con las siguientes versiones:

*  *Python*: 3.10.12
*  *NumPy*:  1.26.4


In [ ]:
!pip install rlxcrypt
!wget --no-cache -O session.pye -q https://raw.githubusercontent.com/JuezUN/INGInious/master/external%20libs/session.pye

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.9/297.9 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 35.3 MB/s eta 0:00:00
  Created wheel for imphook: filename=imphook-1.0-py3-none-any.whl size=9421 sha256=17aa7d60292b2839e229545d84c38e32d0e8920c3a0557f3e745e82a9f64be85
  Stored in directory: /root/.cache/pip/wheels/dc/e2/a4/fcb3817d09a2eb047b2b08eb58e7d9140041b0f3f415eb1256
Successfully built imphook


In [9]:
import rlxcrypt
import session

grader = session.LoginSequence("AYVDDCP-GroupMLDS-1-2024-2@tarea_1")

Please enter your UNCode username: cecordobat
Please enter your password: ··········


## **1. Conteo de pedidos**
---

Usted es responsable de la recepción de pedidos en un pequeño negocio en crecimiento. Un día, se produce una gran e inusual cantidad de pedidos por lo que decide usar sus habilidades de programación para realizar esta tarea de una manera más eficiente y automática. Para esto, le asigna a cada uno de los $n$ productos distintos del negocio un código con un número entero de $0$ a $n - 1$ como identificador (ID).

Una de las tareas iniciales que desea realizar en su sistema es tomar la lista de pedidos, que cuidadosamente logró convertir y cargar en un formato digital, y conocer la cantidad total de pedidos que se realizó por cada producto. De esta forma, podrá realizar la solicitud respectiva a sus proveedores.

Suponga que, gracias a la codificación de productos realizada, usted puede obtener una lista con todos los IDs de los productos solicitados fácilmente. A continuación, deberá implementar la función **`conteo_pedidos`**. Esta función debe cumplir con la siguiente especificación:

* La función recibirá como argumento la lista original de IDs de todos los productos pedidos: **`pedidos`**.
* Debe generar y retornar un arreglo con el conteo de veces que se realizó el pedido de cada uno de los productos. El número de pedidos del producto con ID $i$ se debe almacenar en la posición $i$ en el arreglo creado.

Tenga en cuenta que el tamaño del arreglo resultante debe corresponder con el identificador con el número mayor en la lista de **`pedidos`**.


> **Nota:** En este ejercicio se garantiza que la lista ingresada en el momento de la calificación esté compuesta exclusivamente por números enteros entre $0$ y $n - 1$. No obstante, en un escenario real se considera buena práctica validar las posibles entradas del sistema y realizar un análisis de los flujos alternativos que su problema deberá realizar en cada caso posible.

Considere los siguientes ejemplos de ejecución de la función:

```
>>> print(conteo_pedidos(np.array([2, 2, 3, 4, 2, 2])))
[0. 0. 4. 1. 1.]

>>> print(conteo_pedidos(np.array([1, 2, 3])))
[0. 1. 1. 1.]

>>> print(conteo_pedidos(np.array([0])))
[1.]
```

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* Se puede calcular el máximo de un arreglo **`x`** llamando a la función **`np.max(x)`**.
* La función **`np.zeros`** devuelve un arreglo inicializado con ceros.
* Una opción recomendada es recorrer (iterar) el arreglo de **`pedidos`** a medida que construye el arreglo con el conteo.


In [15]:
# FUNCIÓN CALIFICADA: conteo_pedidos(pedidos)
def conteo_pedidos(pedidos):
    """
    pedidos: un arreglo de NumPy con valores enteros no negativos. Contiene IDs de productos pedidos, pueden estar repetidos.

    Retorna un arreglo con el conteo de los IDs del arreglo de pedidos.
    El arreglo resultante codifica cada conteo en su posición de ID correspondiente.
    """
    ### ESCRIBA SU CÓDIGO AQUÍ ###
    # Reemplace la palabra None por el código correspondiente
    # ~ 6 líneas de código

    # Obtenga el valor máximo del arreglo 'pedidos'
    id_max = max(pedidos)

    # Crear un arreglo de conteos inicializado en 0 con un tamaño de id_max + 1
    conteos = np.zeros(id_max + 1, dtype=int)

    # Recorrer la lista de pedidos y actualizar los conteos
    for pedido in pedidos:
        conteos[pedido] += 1

    return conteos

In [16]:
# CELDA DE PRUEBAS
print(conteo_pedidos(np.array([1, 2, 3, 3, 3, 5, 5, 6])))

print(conteo_pedidos(np.array([2, 2, 3, 4])))

print(conteo_pedidos(np.array([1, 2, 3])))

[0 1 1 3 0 2 1]
[0 0 2 1 1]
[0 1 1 1]


La salida de la celda anterior debería ser:
```
[0. 1. 1. 3. 0. 2. 1.]
[0. 0. 2. 1. 1.]
[0. 1. 1. 1.]
```

### **Evaluar código**

In [17]:
grader.run_test("Test 1_1", globals())

Test 1_1


In [18]:
grader.run_test("Test 1_2", globals())

Test 1_2


In [19]:
grader.run_test("Test 1_3", globals())

Test 1_3


In [20]:
grader.run_test("Test 1_4", globals())

Test 1_4


In [21]:
grader.run_test("Test 1_5", globals())

Test 1_5


## **2. Cantidad de material**
---
Cada producto fabricado en su empresa requiere de una cierta cantidad de unidades de materias primas $M_j$. Usted posee una tabla con la cantidad de unidades de cada material $M_j$ que se requiere para la fabricación de cada producto $P_i$. Al igual que con los productos, cada una de las $m$ materias primas están identificadas con números enteros $j$ entre $0$  y $m - 1$ que corresponden a la posición del arreglo. Usted decide calcular automáticamente la cantidad de materia prima requerida para cumplir con un pedido determinado.

Considere el siguiente ejemplo de un pedido:

* Cantidad de unidades por producto:

| $P_0$ | $P_1$ | $P_2$ | $P_3$ |
|-----|-----|-----|-----|
| 2   | 5   | 7   | 8   |

* Cantidad de material $M_j$ necesario para fabricar el producto $P_i$:

|       | $P_0$ | $P_1$ | $P_2$ | $P_3$ |
|-------|-------|-------|-------|-------|
| $M_0$ | 2     | 0     | 2     | 1     |
| $M_1$ | 1     | 1     | 1     | 0     |
| $M_2$ | 2     | 2     | 0     | 2     |


Por ejemplo, para cumplir con este pedido se requiere el siguiente número de unidades del material $M_0$:
* $4$ unidades del material $M_0$ para fabricar $2$ unidades de $P_0$.
* $14$ unidades del material $M_0$ para fabricar $7$ unidades de $P_2$.
* $8$ unidades del material $M_0$ para fabricar $8$ unidades de $P_3$.

Para un total de $26$ unidades de material $M_0$. Si se repite el proceso para los demás materiales el total de materiales que se deben adquirir para este pedido son:


| $M_0$ | $M_1$ | $M_2$ |
|-----|-----|-----|
| 26   | 14   | 30  |

Para esta actividad deberá implementar la función **`cantidad_material`**, que recibe como argumento:
* Lista de cantidad de unidades por producto: **`productos`**.
* Tabla de cantidades de material por producto **`cantidades`**.

A partir de estos $2$ arreglos de *NumPy* la función debe retornar el arreglo con la cantidad de cada material del pedido.

Considere el caso anterior en el ejemplo de ejecución de la función:

```
>>> productos = np.array([2, 5, 7, 8])
>>> cantidades = np.array(
    [[2, 0, 2, 1,],
    [1, 1, 1, 0],
    [2, 2, 0, 2]]  
  )
>>> cantidad_material(productos, cantidades)
array([26, 14, 30])
```

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* Tómese su tiempo para comprender el problema. Este problema puede solucionarse de varias formas. Una de ellas es mediante operaciones de **álgebra lineal**. Para más información, considere el uso de operaciones como la **multiplicación matricial** (operador **`@`**) y el **producto punto** (**`np.dot`**) y aplique la solución usando los conceptos vistos en el taller guiado de *NumPy*.

* Otra solución puede ser mediante operaciones entre vectores y agregaciones como la suma con **`np.sum(axis = ?)`**, definiendo como argumento el eje por el cual se debe realizar la suma (0 para filas, 1 para columnas).



In [24]:
# FUNCIÓN CALIFICADA: cantidad_material(productos, cantidades)
def cantidad_material(productos, cantidades):
    """
    productos: un arreglo de NumPy con dimensión (n,) con valores enteros no negativos.
                Contiene la cantidad pedida de cada uno de los productos.
    cantidades: un arreglo de NumPy con dimensión (m, n) con valores enteros no negativos.
                Contiene las unidades de materia prima (filas) necesarias para la
                fabricación de cada producto (columnas)

    Retorna un arreglo con dimensión (m,) con la cantidad de unidades de materia prima
    requeridas en el pedido.
    """
    ### ESCRIBA SU CÓDIGO AQUÍ ###
    # Reemplace la palabra None por el código correspondiente
    # ~ 1-5 líneas de código

    # Opere las matrices de entrada para obtener el valor requerido.
    productos=np.array(productos)
    cantidades=np.array(cantidades)
    # Tenga en cuenta la dimensión de los arreglos a la hora de realizar las operaciones
    materiales = np.dot(cantidades, productos)
    ### FIN DEL CÓDIGO ###

    return materiales

In [25]:
# CELDA DE PRUEBAS
productos = np.array([0, 5, 1, 2])

cantidades = np.array(
  [[2, 0, 2, 1,],
  [1, 5, 1, 0],
  [3, 2, 0, 0],
  [2, 2, 0, 2]]
)

cantidad_material(productos, cantidades)

array([ 4, 26, 10, 14])

La salida de la celda anterior debería ser:
```
array([ 4,  26, 10, 14])
```

### **Evaluar código**

In [26]:
grader.run_test("Test 2_1", globals())

Test 2_1


In [27]:
grader.run_test("Test 2_2", globals())

Test 2_2


In [28]:
grader.run_test("Test 2_3", globals())

Test 2_3


In [29]:
grader.run_test("Test 2_4", globals())

Test 2_4


In [30]:
grader.run_test("Test 2_5", globals())

Test 2_5


## **3. Cálculo de costos**
---
¡Buen trabajo! Con la ayuda de *NumPy* logró obtener el conteo de pedidos por cada producto y la cantidad de material necesario para fabricarlos. Ahora, para fabricar el producto $P_i$ debe realizar un pedido al proveedor de las materias primas necesarias para construirlo.

La empresa tiene un convenio con el proveedor por medio del cual se aplica un descuento de un porcentaje $D$ en materiales cuando se adquieren por lo menos $L$ unidades.

Por ejemplo, retomando uno de los ejemplos anteriores, teníamos la cantidad de materiales que solicitar al proveedor:

| $M_0$ | $M_1$ | $M_2$ |
|-----|-----|-----|
| 26   | 14   | 30  |

Ahora también conocemos una lista de precios del proveedor por cada material:

| $M_0$ | $M_1$ | $M_2$ |
|-----|-----|-----|
| \$5.0   | \$3.0   | \$4.5  |

En este caso, el valor estipulado en el convenio para $L$ es 15 y el de $D$ de $0.2$ ($20\%$).

Entonces, el costo total del $M_0 = 5.0 \cdot 26 = \$130$. Adicionalmente, dado que se pidieron más de $15$ unidades aplica el descuento del $20\%$ de descuento, para un valor final de \$$104$.

Repetimos el proceso para los demás materiales y obtenemos el siguiente resultado:

| $M_0$ | $M_1$ | $M_2$ |
|-----|-----|-----|
| 104.0   | 42.0   | 108.0  |

Por lo tanto, el costo total del pedido es de \$$254.0$

Su tarea es implementar la función **`costo_pedido`**, que recibe como argumento:

* Lista original de pedidos individuales **`pedidos`**.
* Tabla de cantidades de material por producto **`cantidades`**.
* Lista de costos por material **`costos`**.
* Descuento $D$ **`descuento`**. (Número real entre $0.0$ y $1.0$)
* Mínimo de tamaño del lote $L$ **`lote`**. (Número entero mayor o igual que $0$)

A partir de esto deberá calcular el **costo total** del pedido.

Considere el siguiente ejemplo de ejecución de la función:

```
>>> pedidos = np.array([0, 0, 1, 2, 2, 2, 2, 2, 3])
>>> cantidades = np.array(
      [[2, 0, 2, 1,],
      [1, 1, 1, 0],
      [2, 2, 0, 2]]  
    )

>>> costos = np.array([5.0, 3.0, 4.5])
>>> coste_pedido(pedidos, cantidades, costos, 0.1, 5)
121.5
```

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Pistas</b></font>
</summary>

* Utilice las funciones **`conteo_pedidos`** y **`cantidad_material`** realizadas en los puntos anteriores.
* Recuerde que con *NumPy* puede realizar multiplicación matricial (con **`@`**) y multiplicación elemento a elemento (con **`*`**).
* Puede utilizar selección condicional para realizar operaciones únicamente en los elementos de un arreglo que cumplan una determinada condición.
* La selección condicional sólo requiere que el arreglo tenga la misma dimensión que en el que se realiza la operación. No es necesario que la condición realizada sea con el mismo arreglo.
* El descuento $D$ es un número entre $0.0$ y $1.0$ que se tiene que descontar del total del precio de un material.



In [31]:
# FUNCIÓN CALIFICADA: costo_pedido(pedidos, cantidades, costos, descuento, lote)
def costo_pedido(pedidos, cantidades, costos, descuento, lote):
    """
    pedidos: un arreglo de NumPy con valores enteros no negativos entre 0 y n - 1.
    cantidades: un arreglo de NumPy con dimensión (m, n) con valores enteros no negativos.
    costos: un arreglo de NumPy con dimensión (m, ) con valores reales no negativos.
    descuento: un número real entre 0.0 y 1.0
    lote: un número entero no negativo.

    Retorna un número real no negativo con el costo total del pedido.
    """
    ### ESCRIBA SU CÓDIGO AQUÍ ###
  # Convertir entradas a arreglos de NumPy en caso de que no lo sean
    pedidos = np.array(pedidos)
    cantidades = np.array(cantidades)
    costos = np.array(costos)

    # Calcular la cantidad total de cada materia prima
    cantidad_total = np.dot(cantidades, np.bincount(pedidos, minlength=cantidades.shape[1]))

    # Calcular el costo inicial para cada material
    costo_inicial = cantidad_total * costos

    # Aplicar el descuento si se supera el umbral de lote
    costo_final = np.where(cantidad_total >= lote, costo_inicial * (1 - descuento), costo_inicial)

    # Calcular el costo total del pedido
    costo_total = costo_final.sum()

    return costo_total


In [32]:
# CELDA DE PRUEBAS
pedidos = np.array([0, 0, 1, 2, 2, 2, 2])
cantidades = np.array(
    [[2, 3, 2],
    [1, 5, 1]]
  )
costos = np.array([5.0, 3.0])

costo_pedido(pedidos, cantidades, costos, 0.2, 15)

93.0

La salida de la celda anterior debería ser:
```
93.0
```

### **Evaluar código**

In [33]:
grader.run_test("Test 3_1", globals())

Test 3_1


In [34]:
grader.run_test("Test 3_2", globals())

Test 3_2


In [35]:
grader.run_test("Test 3_3", globals())

Test 3_3


In [36]:
grader.run_test("Test 3_4", globals())

Test 3_4


In [37]:
grader.run_test("Test 3_5", globals())

Test 3_5



## **Evaluación**
**¡Felicitaciones!** Ha terminado la tarea de la Unidad 1. ¡Excelente trabajo!



In [38]:
grader.submit_task(globals())

Test 1_1
Test 1_2
Test 1_3
Test 1_4
Test 1_5
Test 2_1
Test 2_2
Test 2_3
Test 2_4
Test 2_5
Test 3_1
Test 3_2
Test 3_3
Test 3_4
Test 3_5


## **Créditos**

* **Profesor:** [Felipe Restrepo Calle](https://dis.unal.edu.co/~ferestrepoca/)
* **Asistente docente:** Alberto Nicolai Romero Martínez
  
**Universidad Nacional de Colombia** - *Facultad de Ingeniería*